name: fores
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.14.0
  path_provider: ^2.0.11
  image: ^3.0.1
  pdf_render: ^1.4.12
  file_picker: ^8.1.3
  permission_handler: ^11.3.1  
  syncfusion_flutter_pdf: ^27.1.55
  http: ^1.2.2
  pdfx: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata_config.json
